version: '3'
services:
  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=customers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MAX_CONNECTIONS=300
    container_name: postgres-customers
    networks: 
      - nt1Customers 
networks: 
  nt1Customers:
    driver: bridge
