= Contatos API
:example-caption!:
:source-highlighter: highlightjs
:toc: left
:toclevels: 5

== Introdução
Bem-vindo à documentação da API do painel de controle Contatos. Essa documentação da API fornecerá informações suficientes sobre os recursos e as operações suportadas na versão atual. Esta API está seguindo as convenções Restful.

=== Como usar
As solicitações devem ser feitas usando o protocolo HTTP. A interface responde a diferentes métodos, dependendo da ação necessária.

=== HTTP Métodos
Os métodos permitidos são:

|===
| Método | Descrição

| `GET`
| Usado para obter informações sobre um recurso

| `POST`
| Usado para criar informações sobre um recurso

| `PUT`
| Usado para editar informações sobre um recurso

| `DELETE`
| Usado para deletar informações sobre um recurso

|===

[[http-status]]
=== Códigos HTTP
Os códigos HTTP suportados são:

|===
| Código | Descrição

| `200 OK`
| O pedido foi executado com sucesso

| `201 Created`
| O novo recurso foi criado com sucesso

| `204 No Content`
| The server successfully processed the request and is not returning any content

| `400 Bad Request`
|
The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, size too large, invalid request message framing, or deceptive request routing).

|===

= Recursos - Relatórios
Os recursos da API V1 são detalhados nesta seção.

include::city.adoc[]

include::customer.adoc[]

